### ISSUE TITLE
App icon: red does not match

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-android-client#10]
The logo background red and the logo red in the app icon do not match. Can you remove the background  (red) and use the logo alone as app icon?

If we need a different size for the app icon, we can ask the designers for one.

![screenshot_2015-06-12-11-32-31](https://cloud.githubusercontent.com/assets/208246/8127457/49095a3c-10f7-11e5-88ae-9805209933a6.png)

**Comment by arturdryomov** [comment]
It was kind of intentional. [The Material Design guidelines](https://www.google.com/design/spec/style/icons.html#icons-product-icons) have certain rules regarding the product icon. In the ideal situation the hawk should should be adapted to the suggested paper-like style. At this point I just threw it on a rectangle to be a little bit more “material” :-)

**Comment by pilhuhn** [comment]
Then perhaps use some different color - that is not too close here? The red just looks too much like "tried and not achieved" (to me).

Can you specify the exact rules to follow for "adapted to the suggested paper-like style", so that the Designers could have a look?

**Comment by arturdryomov** [comment]
> Then perhaps use some different color - that is not too close here? The red just looks too much like "tried and not achieved" (to me).

Well, it was the most pleasant one that wouldn’t completely meld with the icon. Would you prefer a more dark or more light one?

> Can you specify the exact rules to follow for "adapted to the suggested paper-like style", so that the Designers could have a look?

The link above is the best I can provide. [Google apps](https://play.google.com/store/apps/dev?id=5700313618786177705) are a great example.

**Comment by danielpassos** [comment]
I'll work in a new app icon
