### ISSUE TITLE
Wrong Navigation Item Checked 

### ISSUE THREAD

**Issue by sagar15795** [hawkular/hawkular-android-client#100]
![ezgif com-resize](https://cloud.githubusercontent.com/assets/5468111/23577265/5fe276be-00e0-11e7-941e-a054fcdf839e.gif)

When I return from setting option to the DrawerActivity, I found that setting option is still checked. This issue is happening with Help & feedback and Explorer option.

**Comment by sagar15795** [comment]
I am Woking on it.

**Comment by KeenWarrior** [comment]
Fixed with #101
