### ISSUE TITLE
Aerogear unified push server integration is outdated

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#104]
Aerogear unified push server integration is needed to be updated. In new code android client will receive config for connection from REST endpoint instead of hard coding it in app

**Comment by shubhamvashisht** [comment]
I will do it @garg-anuj

**Comment by KeenWarrior** [comment]
That will be too big chunk to be taken in initial stage. Lets break in chucks for that

**Comment by shubhamvashisht** [comment]
That will be very helpful.

**Comment by shubhamvashisht** [comment]
What is the first task?

**Comment by KeenWarrior** [comment]
Getting some understanding of https://github.com/jboss-mobile/unified-push-helloworld for now

Then we will first make hard coded system work again before going to next stage

**Comment by shubhamvashisht** [comment]
OKAY @garg-anuj

**Comment by danielpassos** [comment]
@shubhamvashisht @garg-anuj ping me if you need some help on it

**Comment by KeenWarrior** [comment]
@danielpassos Surely we will need your help :)

I was just waiting for monday to come
