### ISSUE TITLE
On alerts screen + action is confusing

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#105]
On alerts fragment plus action denoting id `show_hide_res` for showing and hiding toggle for resolved alert should be placed in overflow where its title should change according to the state.

Titles should be `Show Resolved` and `Hide Resolved`

**Comment by sauravvishal8797** [comment]
@garg-anuj Would like to work on it.

**Comment by KeenWarrior** [comment]
@sauravvishal8797 Thanks

**Comment by sauravvishal8797** [comment]
@garg-anuj You're welcome.
