### ISSUE TITLE
Auth issues are not shown in UI

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-android-client#11]
So I just updated the binary after PR#9 and when I started Hawkular.app, it shows me the URL
and a proceed button. Clicking it seems to have no effect.

`adb logcat` shows

```
D/LauncherActivity( 4897): Authorization :: Failure...
D/LauncherActivity( 4897): AuthorizationException{error=invalid_grant}
D/LauncherActivity( 4897):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:277)
D/LauncherActivity( 4897):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
D/LauncherActivity( 4897):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
D/LauncherActivity( 4897):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
D/LauncherActivity( 4897):  at android.os.AsyncTask$2.call(AsyncTask.java:288)
```

I think the app should in this case redirect to the Auth-Login dialog again.
Otherwise, if the credentials are still valid, that screen should probably be skipped and changing the server should be a menu option.

**Comment by arturdryomov** [comment]
Did it get any better in recent versions?

**Comment by pilhuhn** [comment]
Server says 

```
10:05:58,941 WARN  [org.keycloak.protocol.oidc.endpoints.TokenEndpoint] (default task-2) Invoking deprecated endpoint http://172.31.7.7:8080/auth/realms/hawkular/tokens/refresh
10:05:58,943 WARN  [org.keycloak.events] (default task-2) type=REFRESH_TOKEN_ERROR, realmId=hawkular-realm, clientId=hawkular-ui, userId=null, ipAddress=172.31.7.135, error=invalid_token
```

**Comment by ming13** [comment]
Android version is 5.0.2.

**Comment by danielpassos** [comment]
I also got it yesterday on my device Nexus 5 / Android 5.1.1

**Comment by pilhuhn** [comment]
What I am saying now is probably unfair to @ming13 , I am glad that @danielpassos also saw this.

@danielpassos Is this something where AG could be improved - e.g. have an error callback to be used?

**Comment by danielpassos** [comment]
@pilhuhn I thought we had a callback for it. Let me check

**Comment by arturdryomov** [comment]
Seems like an issue with authorization token refreshing. I’ve posted it upstream to AeroGear.

https://issues.jboss.org/browse/AGDROID-490

**Comment by arturdryomov** [comment]
Sent a couple of PR to AeroGear to fix AGDROID-490, but `invalid_grant` can be a Keycloak-related issue.

https://issues.jboss.org/browse/AGDROID-245

**Comment by arturdryomov** [comment]
![Another](http://media.tumblr.com/tumblr_m76y3u29WF1rnn7li.gif)

https://issues.jboss.org/browse/AGDROID-497

**Comment by danielpassos** [comment]
👍
