### ISSUE TITLE
Create Trigger Detail Fragment to present detail of individual trigger

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#112]
There is need of Trigger Detail Fragment similar to Alert Detail Fragment. Right now just create Fragment and pass trigger to it. Then toast whole JSON for completing this issue.

Small, Simple and Spicy

**Comment by shubhamvashisht** [comment]
i would like to work on this. @garg-anuj

**Comment by KeenWarrior** [comment]
@shubhamvashisht  Go on :)
