### ISSUE TITLE
Add license header formatting and checking in gradle

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#114]
Use https://github.com/hierynomus/license-gradle-plugin

One step toward #103

**Comment by KeenWarrior** [comment]
Take a look at  https://github.com/feedhenry-templates/helloworld-android-gradle/blob/master/app/build.gradle#L1-L3

and  https://github.com/feedhenry-templates/helloworld-android-gradle/blob/master/app/build.gradle#L48-L51

**Comment by KeenWarrior** [comment]
Do not forget to include these excludes

https://github.com/hawkular/hawkular-android-client/blob/master/pom.xml#L82-L88

**Comment by sauravvishal8797** [comment]
@garg-anuj Would like to work on this.

**Comment by KeenWarrior** [comment]
@sauravvishal8797 Go for it
