### ISSUE TITLE
Replace GCM by FCM

### ISSUE THREAD

**Issue by danielpassos** [hawkular/hawkular-android-client#119]
There is some variable and properties using `GCM` instead of `FCM`. Since `GCM` is replaced by `FCM` we should also replace that variables and properties

**Comment by shubhamvashisht** [comment]
Would like to it @danielpassos

**Comment by danielpassos** [comment]
@shubhamvashisht Go ahead!

**Comment by KeenWarrior** [comment]
@shubhamvashisht What is the status?
