### ISSUE TITLE
Create a toggle to represent and change state of trigger from TriggersActivity

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#124]
- This issue will need #113 to finish first
- Crate a toggle in place of initial popup area

**Comment by KeenWarrior** [comment]
@shubhamvashisht You can go for it.

**Comment by shubhamvashisht** [comment]
@garg-anuj  Thanks

**Comment by KeenWarrior** [comment]
@shubhamvashisht Read data type `Trigger` http://www.hawkular.org/docs/rest/rest-alerts.html#Trigger
We would need create a PUT call changing `enabled` attribute when toggle is switched.

Steps would be
- Create toggle UI
- Create PUT endpoint call for method Trigger
- Create callback

**Comment by shubhamvashisht** [comment]
@garg-anuj  please check

**Comment by shubhamvashisht** [comment]
@garg-anuj  i need help in the feature you suggested for disabling toggles when state gets changed.

**Comment by KeenWarrior** [comment]
@shubhamvashisht Thanks
