### ISSUE TITLE
Kill AuthorizationActivity

### ISSUE THREAD

**Issue by danielpassos** [hawkular/hawkular-android-client#127]
Today we have `LoginActivity` and `AuthorizationActivity` doing almost the same think. I wanna kill `AuthorizationActivity` in favor of `LoginActivity`

**Comment by shubhamvashisht** [comment]
@danielpassos  need to move HOST  and PORT EditTexts to loginActivity.

**Comment by shubhamvashisht** [comment]
should i? @danielpassos

**Comment by danielpassos** [comment]
@shubhamvashisht No, I'm on it!

**Comment by m-murad** [comment]
@danielpassos 
Should I proceed

**Comment by danielpassos** [comment]
@free4murad Hold on. I'm finishing it. The link was only to you keep in touch when it done you are free to starts #76

**Comment by m-murad** [comment]
@danielpassos 
In `LoginActivity` if we switch to landscape mode, the fields for username and password are not visible.
Please take care of this too, or if you want I can do it.
Thanks

**Comment by danielpassos** [comment]
@free4murad It's a little on hold because of another things I need to do. Feel free to test it on my branch https://github.com/danielpassos/hawkular-android-client/tree/kill-auth and send a PR there if needs

**Comment by m-murad** [comment]
@danielpassos 
Sure

**Comment by KeenWarrior** [comment]
Closed with  #225
