### ISSUE TITLE
Use vector drawables instead of PNGs.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#133]
We can replace the PNGs with their SVG counterparts. This will reduce the apk size.
Also we can compress images using `pngcrusher` to reduce the size of images.

**Comment by KeenWarrior** [comment]
That will be nice. But you should talk to @danielpassos before starting to work on this one

**Comment by danielpassos** [comment]
@free4murad fell free to replace images by `SVG` but I'd like to use only vectores from [Material Icons](https://material.io/icons). You can import/use it directly from the Android Studio without need any other things like `pngcrusher`

File > New > Vector Asset

<img width="1440" alt="Android Studio Menu, Vector Assets" src="https://cloud.githubusercontent.com/assets/13337/23796947/539631a2-057c-11e7-9347-f5903bd257cc.png">

![Vector Assets screen](https://cloud.githubusercontent.com/assets/13337/23796980/70b529c8-057c-11e7-9637-5796aa580403.png)

**Comment by m-murad** [comment]
@danielpassos 
I wan to use `pngcrusher` for images like 
![screen shot 2017-03-10 at 7 17 44 pm](https://cloud.githubusercontent.com/assets/17262180/23797519/47bc05a6-05c6-11e7-8683-c63b465da1c2.png)

in the above case we can reduce the image size from `33.1 KB` to `9.9 KB`

**Comment by danielpassos** [comment]
@free4murad I got you point, but.... IMHO we should also move the logo (and all images/icons) for SVG. That is why I said `pngcrusher` should be not necessary

**Comment by pilhuhn** [comment]
The logo is available in SVG from http://design.jboss.org/hawkular/logo/final/
