### ISSUE TITLE
Update hawkular logo

### ISSUE THREAD

**Issue by danielpassos** [hawkular/hawkular-android-client#134]
We should update the hawkular logo to a vector. Logos are available [here](http://design.jboss.org/hawkular/logo/final/) in any format like @pilhuhn commented [here](https://github.com/hawkular/hawkular-android-client/issues/133#issuecomment-285677766)

**Comment by KeenWarrior** [comment]
@danielpassos Should I close #10 then?

**Comment by danielpassos** [comment]
@garg-anuj Nopz. I'm working on it now and going to send a new one!

**Comment by danielpassos** [comment]
@garg-anuj This one is for #10 => https://github.com/hawkular/hawkular-android-client/pull/136
