### ISSUE TITLE
Click not properly configured on list items.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#144]
In list items (e.g. list items of TriggersFragment) the onclick is not properly configured.
If we click on the extremes of the list (top, bottom, left) the desired event doesn't occur.

Should I send a PR.

**Comment by danielpassos** [comment]
@free4murad Sure!

**Comment by KeenWarrior** [comment]
@free4murad You can join https://gitter.im/hawkular/GSoC for any help ;)
