### ISSUE TITLE
force close in explorerActivity (unable to launch metricActivity).

### ISSUE THREAD

**Issue by shubhamvashisht** [hawkular/hawkular-android-client#145]
![g_20170315_1903103](https://cloud.githubusercontent.com/assets/16692282/23951209/86c31b72-09b3-11e7-80c6-7b5b1e2c38e6.gif)

LOGCAT: http://pastebin.com/KqE0Z40d

**Comment by KeenWarrior** [comment]
I thought it will remain uncaught from you guys few days :smile:

**Comment by KeenWarrior** [comment]
@pg301 Would like to work on it?

**Comment by pg301** [comment]
@garg-anuj Sure :)

**Comment by pg301** [comment]
@garg-anuj Done 👍 

P.S. One 's' makes a lot of difference ;) 

 [
![screenshot_1489596066](https://cloud.githubusercontent.com/assets/10026907/23959880/660047f2-09cc-11e7-80d4-1bc3b157c8a8.png)
](url)
