### ISSUE TITLE
Disolving FavTriggersFragment into TriggersFragment

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#147]
I propose dissolving `FavTriggersFragment` into `TriggersFragment`. `FavTriggersFragment` and `TriggersFragment` have everything in common except at `TriggersFragment` data come from rest api at `FavTriggersFragment` data come from store.

**Comment by m-murad** [comment]
Can I work on this

**Comment by pg301** [comment]
@garg-anuj I would like to work on it as well.

**Comment by KeenWarrior** [comment]
@free4murad Lets pick only one issue at a time. Please finish #144 for next issue.

**Comment by KeenWarrior** [comment]
@pg301 Go for it

**Comment by pg301** [comment]
@garg-anuj Thanks 👍

**Comment by pg301** [comment]
![demo2](https://cloud.githubusercontent.com/assets/10026907/23986802/0a5b8ad0-0a4c-11e7-93b4-7ac76cb2bd60.gif)
@garg-anuj I have replaced FavTriggerFragment but there is a small glitch now. Only when I refresh, this update comes. I have added the code in setUpForcedTrigger. Can you please guide me through.

**Comment by pg301** [comment]
@garg-anuj I think I fixed it. I removed setupstate method from triggerFragment

**Comment by KeenWarrior** [comment]
@pg301 What you can do is place the PR with WIP (Work in progress) tag. So that we can help you out better
