### ISSUE TITLE
Move checkstyle from maven goal to gradle

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#156]
Use [gradle plugin](https://docs.gradle.org/current/userguide/checkstyle_plugin.html) to shift checkstyle to gradle

[checkstyle.xml](https://raw.githubusercontent.com/hawkular/hawkular-build-tools/master/build-tools/src/main/resources/hawkular-checkstyle/checkstyle.xml)

[Checkstyle settings](https://github.com/hawkular/hawkular-parent-pom/blob/master/pom.xml#L99-L139)

**Comment by pg301** [comment]
@garg-anuj can I try

**Comment by KeenWarrior** [comment]
@pg301 Sure

**Comment by shubhamvashisht** [comment]
i would like to  work.

**Comment by KeenWarrior** [comment]
@shubhamvashisht One work at a time ;) I will get something else for you when you finish this one

**Comment by KeenWarrior** [comment]
@shubhamvashisht I mean your present one :smile:

**Comment by shubhamvashisht** [comment]
@garg-anuj  Alright sir

**Comment by sauravvishal8797** [comment]
@garg-anuj I would also like to work on it.

**Comment by janakamarasena** [comment]
@garg-anuj I would also like to work on this.

**Comment by danielpassos** [comment]
@sauravvishal8797 @janakamarasena Sorry, @pg301 Is already on it. I just assigneed that to her to avoid confusion

**Comment by KeenWarrior** [comment]
Closed with #159
