### ISSUE TITLE
Bug in backpress.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#162]
Current behavior - If the navigation bar is open and user presses back key the app is closed.

Expected behaviors - If the navigation bar is open and user presses back key the navigation bar should close.

Should I send a PR.

**Comment by KeenWarrior** [comment]
@free4murad Go on

**Comment by danielpassos** [comment]
@garg-anuj Please don't forgot to assigned the issue when say "Go on" to avoid confusion
