### ISSUE TITLE
Replace ListView with RecyclerView.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#165]
The app is still using ListView.
We should use RecyclerView instead. RecyclerView will give us better control over list items and add animations in future.

Should I send a PR.

**Comment by pg301** [comment]
@free4murad Good suggestion, but I think recycler view is beneficial in case of complex list items. In our current setting the list items are fairly simple so using ListView will be the correct choice.

**Comment by shubhamvashisht** [comment]
perfomance wise there is no noticeable difference between RecyclerView and ListView and as @pg301  said that current listitems are simple enough.. i dont think there is need to change it.

**Comment by KeenWarrior** [comment]
@danielpassos Can you please suggest what will be better?

**Comment by m-murad** [comment]
@shubhamvashisht @pg301 
Currently the list items are simple, but as me add more features they will become more and more complex. We have to replace the ListView at some point in future. Why not now.
Also the ListView doesn't support animations. 

Any way, lets see what @garg-anuj and @danielpassos think.

**Comment by shubhamvashisht** [comment]
@free4murad  can you name any such feature which is not simple to implement with listView but with recyclerView except Animations.?

**Comment by Sanyam96** [comment]
RecyclerView is much more powerful, flexible and a major enhancement over ListView.
 LayoutManager - we can implement LinearLayoutManager, StaggeredlayoutManager, GridLayoutManager, and the best thing is we can do it dynamically as well
Item Animation and Decorator is also another factor.
 AdapterView.OnItemClickListener interface in ListView but  RecyclerView gives much more power and control to its developers by the RecyclerView.OnItemTouchListener but it complicates things a bit for the developer.
RecyclerView is much more customizable than the ListView and gives a lot of control and power to its developers.

**Comment by m-murad** [comment]
@Sanyam96 
Thanks for note.
@shubhamvashisht 
Let the project maintainers decide if the changes are to be made or not.

**Comment by danielpassos** [comment]
@free4murad Go ahread
