### ISSUE TITLE
Ripple effect missing.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#168]
In AlertsFragment the list items are clickable but the ripple effect is missing.
We should add the ripple effect to the list items.

I have solved this, should I send a PR?

**Comment by pilhuhn** [comment]
On 19 Mar 2017, at 19:56, Murad wrote:

> In AlertsFragment the list items are clickable but the ripple effect 
> is missing.
> We should add the ripple effect to the list items.

What is this ripple effect?

> I have solved this, should I send a PR?

In cases you already have a patch, you can directly submit a PR and 
don't need to open an issue before.

**Comment by m-murad** [comment]
@pilhuhn 
This is a ripple effect.
[image](https://github.com/traex/RippleEffect/blob/master/demo.gif)

We are following this pattern in `TriggersFragment`

**Comment by pilhuhn** [comment]
On 19 Mar 2017, at 20:31, Murad wrote:

> @pilhuhn
> This is a ripple effect.
> [image](https://github.com/traex/RippleEffect/blob/master/demo.gif)

Ok, cool. Didn't know it is called that way.

-- 
hwr@pilhuhn.de  m:0179/207 4919  b:http://pilhuhn.blogspot.com
