### ISSUE TITLE
Lists are not update.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#171]
The lists in the projects are not being updated instantly.
for e.g In Favorite `TriggersFragment` the trigger list is not updated instantly.
Steps to reproduce
1. Open Favorite `TriggersFragment`.
2. Click on an item. (`TriggerDetailFragment`) will open.
3. Remove the Trigger from favorite by clicking on the Heart shaped button.
4. Press back button. (Favorite `TriggersFragment` will open)
5. The item removed from the favorites is still in the list and will not disappear until you refresh the list.

Same is happening with Alerts list when we mark an alert `Resolve` or `Acknowledge` from `AlertDetailFragment`.

**Comment by KeenWarrior** [comment]
Closed with #172
