### ISSUE TITLE
Providing a search view.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#173]
We can provide search view in the toolbar so that the user can search for Metrics, Triggers or Alerts.

If this is an intended function I would like to work on this.

**Comment by pilhuhn** [comment]
On 20 Mar 2017, at 0:51, Murad wrote:

> We can provide search view in the toolbar so that the user can search 
> for Metrics, Triggers or Alerts.
>
> If this is an intended function I would like to work on this.

Sounds like a good idea to me.
Perhaps allow via a drop-down in the magnifier to limit the scope of 
search

**Comment by m-murad** [comment]
@pilhuhn 
Sorry but I didn't get you.

**Comment by pilhuhn** [comment]
On 20 Mar 2017, at 8:41, Murad wrote:

> @pilhuhn
> Sorry but I didn't get you.

I think/thought I recall, that the search widget
https://developer.android.com/guide/topics/search/search-dialog.html#UsingSearchWidget

allows/allowed to 'click' on the magnifier class to get a drop down, 
where you could
offer all/alerts/metrics/... in the drop-down to basically give a scope 
on what to search
for.

Imagine you search for the letter 'e' - that could result in thousands 
of items from all over the place.
Now when it is possible to limit the scope to "metric", the list would 
be shorter and the user would not need to go through alerts or inventory 
items.

But apparently that click on magnifier was a dream of mine.
It could still make sense to provide the context e.g. by a prefix to the 
search term
metric:e  inv:foo  alert:bar trigger:one to limit the scope of the 
search. This is just an
idea.

**Comment by m-murad** [comment]
@pilhuhn 
How about the search option will show only the results from the current fragment.

e.g.
If you are in TriggersFragment and search something. The search will only show Triggers.
Similarly if you in AlertsFragment and search something. The search results will only contain Alerts.

What do you think?

**Comment by pilhuhn** [comment]
On 20 Mar 2017, at 9:48, Murad wrote:

> @pilhuhn
> How about the search option will show only the results from the 
> current fragment.

Makes sense.

**Comment by m-murad** [comment]
@pilhuhn 
I will start working on it then.
One more thing.
Can you tell me who I should contact to write a proposal for this project.

**Comment by KeenWarrior** [comment]
@free4murad I will suggest to provide small and often PRs so we can have good feedback cycle

**Comment by m-murad** [comment]
@garg-anuj 
Actually I was working on issue #188 .
The PR which I will send changes several file heavily and needed a lot of testing. Was busy with testing. (Didn't want to send a faulty PR.)

Will send a PR today

**Comment by m-murad** [comment]
@garg-anuj
I think we can close this now.

**Comment by KeenWarrior** [comment]
yup
