### ISSUE TITLE
Toast while making favorite and when toggle button is clicked

### ISSUE THREAD

**Issue by anant-dev** [hawkular/hawkular-android-client#174]
we can add a toast of short description to let user know what happened, on clicking the heart in individual trigger and on clicking the toggle button for respective trigger.

**Comment by danielpassos** [comment]
I'd like to use `Snackbar` instead of `Toast`

**Comment by anant-dev** [comment]
@danielpassos Ok i will make the changes and make a new pr

**Comment by danielpassos** [comment]
@anant-dev You don't need to make a new one. You can update the current one!

**Comment by shubhamvashisht** [comment]
@danielpassos sir, guided by @garg-anuj i am already on something similar to it. i will update the issue #124 .

**Comment by danielpassos** [comment]
ok

**Comment by anant-dev** [comment]
@danielpassos  i have updated the pr please review.
