### ISSUE TITLE
App should have a Splash Screen

### ISSUE THREAD

**Issue by anant-dev** [hawkular/hawkular-android-client#175]
The app should have a splash screen to appear while opening it, in place of a blank white screen which currently appears.

**Comment by pilhuhn** [comment]
On 20 Mar 2017, at 11:59, Anant Singh wrote:

> The app should have a splash screen to appear while opening it, in 
> place of a blank white screen which currently appears.

I am not convinced. See 
https://cyrilmottier.com/2012/05/03/splash-screens-are-evil-dont-use-them/
Better work on accelerating the startup until the point where the real 
UI is shown.

**Comment by m-murad** [comment]
@pilhuhn 
Google has written some articles about app start time.
We can look into that.

**Comment by anant-dev** [comment]
@pilhuhn  Splash screen is there to give the user immediate feedback that the app has started and is loading. Even google has it in there material design doc - https://material.io/guidelines/patterns/launch-screens.html#launch-screens-branded-launch
The white screen if stays long can create a sense of uncertainity in user so  we can consider putting it.

@free4murad  app start time depends on the api fetch time and internet connectivity (speed), unless we store previous data in the cache (which increases app size) that we can show at the loading time.

**Comment by m-murad** [comment]
@anant-dev 
For what I remember according to google guidelines we should first try to decrease the app launch time. After we try every single method of doing that and the launch time is still long then we should introduce a SplashScreen.

I think we should try to reduce the reduce the app launch time, if that fails then add a SplashScreen.

(Just an opinion.)

**Comment by danielpassos** [comment]
Do we load anything before user login? If not. -1 for that

**Comment by pilhuhn** [comment]
@anant-dev If we only show the UI after fetching some remote data, then we need to fix this. Show the UI and then inside the UI have a load indicator that tells what the system is doing.
Perhaps even in a text field, so that it looks like how gradle is showing its actions.

**Comment by anant-dev** [comment]
@pilhuhn this is the correct solution to avoid splash screen :+1:

**Comment by KeenWarrior** [comment]
Closing it on ref of #179
