### ISSUE TITLE
Add show/hide password option in login screen. 

### ISSUE THREAD

**Issue by shubhamvashisht** [hawkular/hawkular-android-client#189]
Adding show/hide password option in login screen just for convenience.
Hidden:
![screenshot_1490451548](https://cloud.githubusercontent.com/assets/16692282/24322995/513c74a6-1194-11e7-90b1-f239cd5018e2.png)
Shown:
![screenshot_1490451553](https://cloud.githubusercontent.com/assets/16692282/24322999/6d6fe734-1194-11e7-8103-99c14fc2be56.png)

**Comment by shubhamvashisht** [comment]
@garg-anuj  please check.

**Comment by m-murad** [comment]
@shubhamvashisht
This functionality is awesome. 
But I suggest you wait for @danielpassos to complete #127

**Comment by danielpassos** [comment]
Or send it directly in my work branch => https://github.com/danielpassos/hawkular-android-client/tree/kill-auth

**Comment by shubhamvashisht** [comment]
@danielpassos sent

**Comment by KeenWarrior** [comment]
Closed with https://github.com/danielpassos/hawkular-android-client/pull/3
