### ISSUE TITLE
Show more details for trigger.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#190]
While adding a few triggers, I noticed that `TriggerFragment` isn't showing all the details about the trigger. Not even the correct details in some cases.
We should update this.
Also more details should be displayed in the `TriggerDetailsFragment`

@danielpassos @pilhuhn @garg-anuj 
If this is intended at this point should I send a PR?

**Comment by danielpassos** [comment]
Can you be more specific what do you wanna add to @pilhuhn confirm if it's really necessary

**Comment by KeenWarrior** [comment]
@free4murad These are part of GSoC stuff thats why I haven't put words about it yet. So keep calm. Long road ahead :wink:
