### ISSUE TITLE
We should remove stylecheck from travis.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#191]
We recently moved the stylecheck to gradle.
But the travis is still checking for style. Its no longer needed there, we should remove it from the `travel.yml` file.

Should I send a PR?

**Comment by danielpassos** [comment]
Sure!

**Comment by KeenWarrior** [comment]
@free4murad Hey we have moved checkstyle from maven to gradle that too is not 100% complete. 

So there will be movement of checkstyle from maven to gradle inside travis shell but it will not be removed.

**Comment by m-murad** [comment]
@garg-anuj 
Sure, got your point. Should I close this issue?

**Comment by KeenWarrior** [comment]
@free4murad Yes
