### ISSUE TITLE
RecyclerView.Adapter are not working properly in tests

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#192]
After #188 there is issue in https://github.com/hawkular/hawkular-android-client/blob/master/mobile/src/androidTest/java/org/hawkular/client/android/adapter/AlertsAdapterTester.java and https://github.com/hawkular/hawkular-android-client/blob/master/mobile/src/androidTest/java/org/hawkular/client/android/adapter/MetricsAdapterTester.java

**Comment by KeenWarrior** [comment]
@free4murad Cure it ASAP :wink:

**Comment by m-murad** [comment]
Sure, will send a PR in an hour or 2

**Comment by KeenWarrior** [comment]
Closed with #193
