### ISSUE TITLE
Use Codacy to check the quality of PRs.

### ISSUE THREAD

**Issue by m-murad** [hawkular/hawkular-android-client#196]
We can use [Codacy](https://www.codacy.com) to check the quality of the Pull Requests.
Codacy will find errors, use of unused imports, variables etc in a PR and report them.

@danielpassos @pilhuhn @anuj1708 
What do you guys think about this?

**Comment by pilhuhn** [comment]
On 5 Apr 2017, at 23:37, Murad wrote:

> We can use [Codacy](https://www.codacy.com) to check the quality of 
> the Pull Requests.
> Codacy will find errors, use of unused imports, variables etc in a PR 
> and report them.
>
> @danielpassos @pilhuhn @anuj1708
> What do you guys think about this?

Sounds like a good idea - I like it

**Comment by anuj1708** [comment]
+1

@murad, What are other alternatives for Codacy?

Regards
Anuj Garg

**Comment by KeenWarrior** [comment]
+1 @free4murad , What are other alternatives for Codacy?

**Comment by m-murad** [comment]
@garg-anuj 
I haven't used service other than `Codacy`.
I looked on the web and found a similar service `Sonarqube`

But Codacy is popular than others.

**Comment by pilhuhn** [comment]
I have enabled it and it already commented on the open Pull requests.
Let's see how this goes.

**Comment by pg301** [comment]
@free4murad Good Idea 👍

**Comment by m-murad** [comment]
@pilhuhn 
Nice

**Comment by m-murad** [comment]
I am closing this then.
