### ISSUE TITLE
Fix Uris.getUri

### ISSUE THREAD

**Issue by danielpassos** [hawkular/hawkular-android-client#21]
`Uris.getUri(@NonNull String path)` is replacing `https://agpush-dpassos.rhcloud.com/ag-push/` by 
`/https%3A%2F%2Fagpush-dpassos.rhcloud.com%2Fag-push%2F`

**Comment by arturdryomov** [comment]
Most likely was a wrong call after the refactoring. Probably fixed via [`d0df3e2b`](https://github.com/hawkular/hawkular-android-client/commit/d0df3e2b225b21437649b3d6c2067c6ffb6c8613).
