### ISSUE TITLE
App crashes in API versions 19 and below 

### ISSUE THREAD

**Issue by pg301** [hawkular/hawkular-android-client#214]
Here's the log: https://paste.ubuntu.com/24405633/

Demo: 
![app crash](https://cloud.githubusercontent.com/assets/10026907/25116429/5d000b1a-242a-11e7-8eee-ed52a6d076d9.gif)

I think I know the fix, can I send a PR for this @garg-anuj

**Comment by KeenWarrior** [comment]
go on

**Comment by KeenWarrior** [comment]
If this is related to login activity. Better send PR to fork of @danielpassos

**Comment by m-murad** [comment]
@pg301 

In `activity_login.xml` you need to replace 
`android:src="@drawable/hawkular_logo"`
with `app:srcCompat="@drawable/hawkular_logo"`.

The error is because we are using vector drawables instead of conventional PNG files.
Why don't you check the whole project for this type of errors.

**Comment by m-murad** [comment]
The same error can be found in 
1. `fragment_trigger_detail.xml` - Line 37

**Comment by pg301** [comment]
@free4murad Thanks for the suggestion. I knew the error, I was just scanning the layouts for similar errors. @garg-anuj since this is not connected to the login acitvity, I will send a PR here only?

**Comment by m-murad** [comment]
@pg301 
Send one PR to @danielpassos branch and one to the main repo.
In my opinion that will be a better think to do.
But confirm with @garg-anuj before you proceed.
