### ISSUE TITLE
Adjust code to new inventory version 

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-android-client#27]
16:55:28,065 WARN  [org.hawkular.inventory.rest](default task-48) RestEasy exception, : javax.ws.rs.NotFoundException: Could not find resource for full path: http://10.33.144.207:8080/hawkular/inventory/6912d4d4-c830-463a-9443-8ecfae03ceaa/environments

The tenant is no longer part of the url and needs to be sent in the header Hawkular-Tenant

**Comment by arturdryomov** [comment]
I would prefer to stick to [public releases](http://www.hawkular.org/downloads.html) just to be more or less stable. `master` of `hawkular/hawkular` is changing too frequently. Actually the authorization screen points at the supported version of Hawkular.

I’ve made [a wiki page](https://github.com/hawkular/hawkular-android-client/wiki/Server) describing the process better. I would point to a Docker image, but it [doesn’t work](http://lists.jboss.org/pipermail/hawkular-dev/2015-June/001190.html)—haven’t heard any comments regarding this actually.

**Comment by pilhuhn** [comment]
On 1 Jul 2015, at 22:42, Artur Dryomov wrote:

> I would prefer to stick to [public 
> releases](http://www.hawkular.org/downloads.html) just to be more or

Well, in theory a public one should show up very soon, which
follows current master. #keepfingerscrossed

**Comment by arturdryomov** [comment]
Yep, I saw there is a demo event tomorrow. I’ll try out `master` anyway.

**Comment by metlos** [comment]
Inventory 0.1.0.Alpha3 which is part of Hawkular 1.0.0.Alpha2 deduces the tenant ID from auth info.

So if you just pass in your credentials, a default tenant ID for that user is deduced from it, no need to pass in any additional headers or anything.

If you would like to use a non-default persona for given user (i.e. you want the user to impersonate an organization), you pass in the persona ID of the organization in the `Hawkular-Persona` header. The tenant ID will again be deduced from that.

Oh, and to point it out explicitly, tenant ID is no longer part of the URL, so `http://10.33.144.207:8080/hawkular/inventory/6912d4d4-c830-463a-9443-8ecfae03ceaa/environments` should read `http://10.33.144.207:8080/hawkular/inventory/environments` which will work as long as the user accessing that URL is authenticated.

**Comment by arturdryomov** [comment]
Implemented via #28.
