### ISSUE TITLE
Alerts categorization

### ISSUE THREAD

**Issue by arturdryomov** [hawkular/hawkular-android-client#31]
At this point alerts are shown without any filtering or categorization, i. e. there are no ways to take a look at alerts only for `https://github.com` or `https://reddit.com`, for example,—only everything you got.

A search for solution leads to both API and UI confusion.
### API

It is possible to filter alerts using trigger IDs and tags. Console uses [filtering based on triggers](https://github.com/hawkular/hawkular/blob/640b86adf45ff8f1f38c48bf6f072fb236021a6c/console/src/main/scripts/plugins/metrics/html/url-list.html#L54) which I personally consider as a hack, because there is no guarantee that the trigger ID will have a format of `{resource-id}_trigger` on an infinite timescale.

Anyway, `GET /alerts` result looks [like that](http://pastie.org/private/y47oftsdoi4bixbndpfcw). As you can see, there is not much to use to determine a category, i. e. a resource in our case.

We can work around for time being the same ways as Console does—it is the solution at this point.
### UI

The current scheme [looks like that](https://github.com/hawkular/hawkular-android-client/wiki/Design).
- Navigation Drawer. Contains “Resources” and “Alerts” sections.
- Resources section. Resources View. Contains resources with resource types as sections. Selecting a resource opens Metrics View. Selecting a metric shows a Metric View.
- Alerts section. Alerts view. Contains alerts. Selecting an alert does nothing.

To filter alerts we need to select a resource first.
- Navigation Drawer. Contains “Resources” and “Alerts” sections.
- Resources section. Resources View. Contains resources with resource types as sections. Selecting a resource opens Metrics View. Selecting a metric shows a Metric View.
- Alerts section. Resources View. Contains resources with resource types as sections. Selecting a resource opens Alerts View.

As you can notice the screen with the Navigation Drawer in the second scenario contains the Resources View all the time, which can lead to confusion.

The closes solution I can thing of is showing “Alerts” and “Resources” as a title of the screen with the Navigation Drawer. This probably will give at least a visual hint of current “mode”.

**Comment by pilhuhn** [comment]
I agree that the current api filter by trigger is limiting. I also believe that some kind of search and filtering is being added as we speak. One of the issues is that Alerts is trying to be generic and could be applicable out of the main Hawkular context.

It may be though that you need to query some properties from Inventory before being able to filter on them in alerts.

With respect to the API, I would like you to clearly state what you need, so that this can be added to Hawkular - especially as you will not be the only client, so others will benefit here as well.

I think what you say wrt the UI makes sense. I guess for alerts one will always have (at least) 2 ways to access them:
- when standing on a resource, one may want to see alerts of that resource (only)
- a generic Alerts screen, that allows to filter down by e.g. severity, age, ack-state and so on.

**Comment by arturdryomov** [comment]
I’m gonna quote @jshaughn and his message on the ML.

> At the alerting level the main ability to categorize, outside of playing games with trigger names and things like that, is provided by Tags.  Tags can be applied to Triggers and are basically [category],name.  You can then query Triggers via tags, and also query alerts via the tags on their owning triggers.
> 
> Because alerts have no inventory context, meaning it does not know about resources, higher level API for tying together Resources/Triggers/Alerts would need to be provided at the Hawkular level.  And that is fine, I think.  So the questions become, "what would a helpful API look like" and "where do we keep the relationships, in alert tags, resource relationships,. etc"?

From my perspective this thought is actually correct. I understand that all modules work as isolated as possible, but some glue should be there to tie things together and provide some sort of context to make all connections work together.

Maybe Inventory can take this role? For example, it already provides some reference to metrics, i. e.

```
GET /hawkular/inventory/{environment}/resources/{resource}/metrics
```

What about a similar thing?

```
GET /hawkular/inventory/{environment}/resources/{resource}/alerts
```

But it is a very interesting question. Probably it is kind of a global one. What sort of abstraction should modules have? How should they communicate together?

**Comment by arturdryomov** [comment]
Implemented, but I’ll keep the issue open to not forget about API improvements.

**Comment by arturdryomov** [comment]
Was reported upstream.

https://issues.jboss.org/browse/HAWKULAR-571
