### ISSUE TITLE
Metric charts

### ISSUE THREAD

**Issue by arturdryomov** [hawkular/hawkular-android-client#33]
It would be great to support different charts for availability and gauges metrics just like Console does. For availability it uses a bar chart and for gauges it uses a line chart.

This will require some determination to find out the type of a metric from the Inventory side. Metrics response looks [like this](http://pastie.org/private/szbaydrsscedelqcyglp9w) and Metric response looks [like this](http://pastie.org/private/hjtgyyoqlndy5zzfu1q) for gauges. As far as I can see there are no proper fields in models to determine the type of a metric.

Of course it is possible hard-code type association, i. e `status.duration.type` is `gauges` and `status.code.type` is `availability`, but Hawkular is not limited to these types.

**Comment by arturdryomov** [comment]
Partially affected by the upstream issue.

https://issues.jboss.org/browse/HAWKULAR-452

**Comment by arturdryomov** [comment]
Another upstream issue.

https://issues.jboss.org/browse/HAWKULAR-453

**Comment by jkremser** [comment]
just a heads up, it was done on the inventory side 2 weeks ago

here is how it looks like:

``` bash
curl -X GET -H 'Content-Type: application/json' 'http://jdoe:password@127.0.0.1:8080/hawkular/inventory/metricTypes/status.code.type' | less
```

``` json
{
  "path" : "/mt;status.code.type",
  "unit" : "NONE",
  "type" : "GAUGE",
  "tenantId" : "28026b36-8fe4-4332-84c8-524e173a68bf",
  "id" : "status.code.type"
}
```

side note:
btw. you may want to present the traits collected by the pinger component for the 'URLtyped' resources:

``` bash
curl -X GET -H 'Content-Type: application/json' 'http://jdoe:password@127.0.0.1:8080/hawkular/inventory/resourceTypes/URL/resources' | less
```

``` json

[ {
  "path" : "/e;test/r;ed646a3334ca891fd3467db131372140",
  "type" : {
    "path" : "/rt;URL",
    "tenantId" : "28026b36-8fe4-4332-84c8-524e173a68bf",
    "id" : "URL"
  },
  "properties" : {
    "trait-collected-on" : 1438609380117,
    "trait-powered-by" : "gws",
    "trait-remote-address" : "64.233.184.94",
    "url" : "http://www.google.com"
  },
  "environmentId" : "test",
  "tenantId" : "28026b36-8fe4-4332-84c8-524e173a68bf",
  "id" : "ed646a3334ca891fd3467db131372140"
} ]
```

**Comment by arturdryomov** [comment]
Sent as #42.

**Comment by arturdryomov** [comment]
Merged.
