### ISSUE TITLE
Multiple accounts vs. personas

### ISSUE THREAD

**Issue by arturdryomov** [hawkular/hawkular-android-client#34]
The very first plan regarding the application included support for multiple accounts. In case with Hawkular it can mean multiple things.
- Accounts. You can imagine it as a tuple `(host, port, authorization token)`. In other words—multiple services and websites, like Google, Apple, Microsoft.
- Personas. Basically you can imagine it as nodes of Account. An account can have multiple personas. In other words—multiple personalities on a single website, like `hawkular.falcon@gmail.com`, `hawkular.dragon@gmail.com`. Google accounts is a great example, because you actually can switch between accounts without a relogin procedure.

We can support both, but it can lead to confusion, because it is possible to achieve Personas scenario using multiple Accounts.

To follow [KISS](http://www.bandjob.com/brawl-uploads/KissLogo_Final_Flat_LR550.jpg), we can just adapt Console scenario and support multiple Personas plus logging out of the account for cases when you want to support multiple Accounts.

**Comment by arturdryomov** [comment]
## Technical perspective.

### Accounts

Just use unique names for `AuthzModules`. Account information can be fetched as follows.

```
$ http GET http://host:port/hawkular-accounts/personas/current --json
```

### Personas

Available personas information can be fetched as follows. The next step is to provide proper HTTP headers, i. e. `Hawkular-Persona` or `Hawkular-Tenant`.

```
$ http GET http://host:port/hawkular-accounts/personas --json
```

**Comment by pilhuhn** [comment]
The persona system in Hawkular follows the GitHub one, where one can act as the GH-user itself or as part of an organization. 
Or G+ where I can post as Heiko or as Hawkular-Org
