### ISSUE TITLE
Refresh access request even after deauth caused by expired refresh token

### ISSUE THREAD

**Issue by openwarrior** [hawkular/hawkular-android-client#53]
Client place a refresh token request in place of auth even after deauth caused by refresh token expiring ( That is after half hour. If app is not being used). But working properly with manual Logout.

On click of "authorize" button. Following HTTP request made.

POST /auth/realms/hawkular/protocol/openid-connect/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; XT1022 Build/LPC23.13-34.8)
Host: 192.168.1.26:8080
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 1107

client_secret=&client_id=hawkular-ui&`grant_type=refresh_token`&refresh_token=eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIyZDA4ZDg0OC0yZWJmLTQ3MWItYTY4Zi1jMDg0MDdkZDE5MmUiLCJleHAiOjE0NTYyMzAzODksIm5iZiI6MCwiaWF0IjoxNDU2MjI4NTg5LCJpc3MiOiJodHRwOi8vMTkyLjE2OC4xLjI2OjgwODAvYXV0aC9yZWFsbXMvaGF3a3VsYXIiLCJhdWQiOm51bGwsInN1YiI6ImE3MDBlMThiLTkzMjQtNDA4Ni04N2IyLTI2MzlmOWE3NDM1MyIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJoYXdrdWxhci11aSIsInNlc3Npb25fc3RhdGUiOiI5ZGMyODkxNi03MDJiLTRmNTktYmIzNi0zNzVjMzI5ZTVhMTkiLCJjbGllbnRfc2Vzc2lvbiI6ImZjYTkwZjc1LTViNWEtNDQ3Mi1iZDM1LTJlZjBkZTQzYTI5MiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ1c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiaGF3a3VsYXItYWNjb3VudHMtYmFja2VuZCI6eyJyb2xlcyI6WyJ1c2VyIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fX0.iooz0ThCa-NbOHVhAp0K_Jq0xXPCiDG7ucPxHqzclow_lTbDzsTPjVt2g1eos90297cjNpgSgoiwbccvVOEvVbWUrz5qaHa0oZOfhR-YRtfXC27ijjGJ9qlT6it3f_IPt8SD1Xxr-J-nfRtdaMg8XQFkox40kwbKXuaP0k64l0C4wKHKvtThPJIEj6FPrSjycWYrD2UQ28J5BYAVJnQzUX-U6u4VLYqAiBKc9NsvXT05WN9KdLZyOS0OiXPQk3bxuvgONuBwqArlcNbLODy_wtW3uufbeHE7N_Gb3A6SEUxWqZ2Bno4-YToCSR7iXPKN_-8pLUDow11P9EXpty6Jlg

And response is

HTTP/1.1 400 Bad Request
Content-Encoding: gzip
Connection: keep-alive
X-Powered-By: Undertow/1
Server: WildFly/10
Content-Type: application/json
Content-Length: 84
Date: Thu, 25 Feb 2016 04:50:18 GMT

**Comment by jpkrohling** [comment]
This should be caught by the Android client and the login form should be shown again to the user. The response body from Keycloak includes an error code and message, so, this could be used to parse this situation. 

But isn't the Android client using key/secrets now, instead of OAuth tokens?

**Comment by openwarrior** [comment]
@jpkrohling Yeah Its right that it is to be caught by android client. But not able to know where its going wrong So placed the issue so every knows about it. 
Key / Secret is still not implemented as auth module implementation pull request  was getting a bit difficult to be merged and there were some stuff to be fixed in the client. So I had to close that pull request. i will work around solution for that and then I will place pull request again :)

**Comment by openwarrior** [comment]
Solved with #56
