### ISSUE TITLE
Checking if url exist

### ISSUE THREAD

**Issue by openwarrior** [hawkular/hawkular-android-client#76]
I think checking for 404 will be still good thing to do on Authorization Activity. As user will not need to come back if there is some mistake. Best will be if we do only http head check for 404

**Comment by m-murad** [comment]
@anuj1708 
can I send a PR for this?

**Comment by KeenWarrior** [comment]
@free4murad Welcome to hawkular community.

currently @danielpassos is working on merging of auth and login activities to 1. So please wait for 1 or 2 days before touching this issue.

**Comment by m-murad** [comment]
@garg-anuj 
Thanks,
Sure I will wait.

**Comment by danielpassos** [comment]
@free4murad related to => https://github.com/hawkular/hawkular-android-client/issues/127

**Comment by m-murad** [comment]
We also need to validate the username and password fields. If the user leaves the two fields blank and presses Login the app should show an error.

**Comment by anant-dev** [comment]
@free4murad we can check this at the user end itself and show a snack bar telling both the fields are compulsory.

**Comment by m-murad** [comment]
That's what I have suggested.

**Comment by danielpassos** [comment]
@garg-anuj, @anant-dev, @free4murad I already did all of that in https://github.com/hawkular/hawkular-android-client/issues/127. You can check it in my branch [kill-auth](https://github.com/danielpassos/hawkular-android-client/blob/kill-auth/mobile/src/main/java/org/hawkular/client/android/activity/LoginActivity.java#L137-L152)

**Comment by m-murad** [comment]
Cool, we are on the same page then +1.

**Comment by danielpassos** [comment]
Already included in #127
