### ISSUE TITLE
Blank Screen when favourite triggers list is empty

### ISSUE THREAD

**Issue by KeenWarrior** [hawkular/hawkular-android-client#92]
Screen should show message about list being empty.

Changes needed to be done in

`src/main/java/org/hawkular/client/android/fragment/FavTriggersFragment.java`

Refer #91 for help.

**Comment by sauravvishal8797** [comment]
@garg-anuj Would like to work on this.

**Comment by KeenWarrior** [comment]
@sauravvishal8797 Go ahead
