### ISSUE TITLE
implement loading spinner during authentication to show progress.

### ISSUE THREAD

**Issue by shubhamvashisht** [hawkular/hawkular-android-client#98]
when we log in to the server there is no visual hint that user is being authenticated. so user tries to click login button again and again in time it takes to log in. so there should be a loading icon or something similar to show when login /authentication is going on.

**Comment by shubhamvashisht** [comment]
I am working on it. @garg-anuj

**Comment by KeenWarrior** [comment]
@shubhamvashisht Go for it
